apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
