apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: platform
  labels:
    app.kubernetes.io/part-of: argocd
data:
  service.slack: |
    token: $slack-token
    channel: '#argo-cd'
  template.app-sync-status: |
    message: |
      Application {{.app.metadata.name}} sync status is {{.app.status.sync.status}}
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
  template.app-health-status: |
    message: |
      Application {{.app.metadata.name}} health status is {{.app.status.health.status}}
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
  trigger.on-sync-status-unknown: |
    - description: Application sync status is Unknown
      oncePer: app.metadata.name
      send:
      - app-sync-status
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-failed: |
    - description: Application sync has failed
      oncePer: app.metadata.name
      send:
      - app-sync-status
      when: app.status.sync.status == 'Failed'
  trigger.on-health-degraded: |
    - description: Application health has degraded
      oncePer: app.metadata.name
      send:
      - app-health-status
      when: app.status.health.status == 'Degraded'
  trigger.on-health-progressing: |
    - description: Application health is progressing
      oncePer: app.metadata.name
      send:
      - app-health-status
      when: app.status.health.status == 'Progressing' 