apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: platform
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  slack-token: "xoxb-your-slack-token-here"  # 여기에 실제 Slack Bot 토큰을 입력하세요 