# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    variable "is_use" {
        type = bool
        default = true
    }

    variable "eks_name" {
        type = string
        default = "donggyu-eks"
    }

    variable "eks_cluster_attr" {
    
    }

    variable "vpc" { 
    
    }

    data "aws_caller_identity" "current" {}
